### ISSUE TITLE
I have more of a comment than a question...

### ISSUE THREAD

**Issue by GraffL** [stollluk/algebraic-geometry#1]
Nachdem ich die Aufgaben jetzt endlich mal etwas ordentlicher gemacht habe, glaube ich aktuell doch nicht mehr, dass man in Aufgabe 4b) braucht, dass A ein Verband ist.
Zumindest sehe ich gerade nicht, wo die Exitenz endlicher Meets/Joins in meinem Beweis eingehen sollte (und mein Gegenbeispiel a ≥ b ≤ c ist jedenfalls keines, weil es hier doch nicht alle Meets gibt (die leere Menge hat keinen Meet))

Anscheinend sieht nLab das auch so ( https://ncatlab.org/nlab/show/complete+lattice ) - bin mir aber nicht sicher, ob ich da alles richtig interpretiere ^^

**Comment by stollluk** [comment]
Ah, richtig, das ist kein Gegenbeispiel, danke für den Hinweis ^^
Ich werde die Voraussetzung aber erst mal nicht wieder abschwächen, vielleicht übersehen wir doch noch etwas..

**Comment by GraffL** [comment]
Inzwischen bin ich mir sicher, dass es funktioniert: https://github.com/GraffL/algebraic-geometry-in-lean/blob/main/src/exercise4.lean#L55 
Also zumindest Max sollte ich damit überzeugen können :D 
(es schadet aber natürlich weiter nichts die Aufgabe so zu lassen wie sie ist :-)

**Comment by stollluk** [comment]
Ist nun endlich geändert.
